name: Deploy AWS CDK Stack

on:
  push:
    branches:
      - aws_backend_init  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  

      # Install dependencies
      - name: Install dependencies
        run: |
          npm install -g typescript
          npm install -g aws-cdk
          npm install -g ts-node
          npm install  # Ensure you install local dependencies
        working-directory: Backend/AWS_SignUp/

      # Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Bootstrapping CDK app
      - name: bootStrap CDK app 
        run: |
          cdk bootstrap
        working-directory: Backend/AWS_SignUp/

      # Deploy AWS CDK Stack
      - name: Deploy AWS CDK Stack
        run: |
          export RDS_ENDPOINT=${{ secrets.ENDPOINT }}
          export RDS_PASSWORD=${{ secrets.PASSWORD }}
          cdk deploy --require-approval never
        working-directory: Backend/AWS_SignUp/
