name: Deploy AWS CDK Stack

on:
  push:
    branches:
      - aws_backend_init  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install dependencies
        run: |
          npm install
        working-directory: Backend/AWS_SignUp/

      - name: Install missing TypeScript types
        run: |
          npm install --save-dev @types/aws-lambda @types/babel__core @types/babel__generator @types/babel__template @types/babel__traverse @types/graceful-fs @types/istanbul-lib-coverage @types/istanbul-lib-report @types/istanbul-reports @types/jest @types/node @types/stack-utils @types/yargs @types/yargs-parser

      - name: Build TypeScript
        run: npm run build
        working-directory: Backend/AWS_SignUp/

      - name: Set permissions for CDK
        run: chmod +x node_modules/.bin/cdk
        working-directory: Backend/AWS_SignUp/

      - name: Install AWS CDK globally (optional but can resolve issues)
        run: npm install -g aws-cdk

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Bootstrapping CDK app
        run: |
          npx cdk bootstrap
        working-directory: Backend/AWS_SignUp/

      - name: Deploy AWS CDK Stack
        run: |
          export RDS_ENDPOINT=${{ secrets.ENDPOINT }}
          export RDS_PASSWORD=${{ secrets.PASSWORD }}
          npx cdk deploy --require-approval never
        working-directory: Backend/AWS_SignUp/

